"""Agregar venta_cobrada y venta_emitida a reserva

Revision ID: 1252d2766698
Revises: 811ebc575b7c
Create Date: 2025-07-04 22:05:52.648400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1252d2766698'
down_revision = '811ebc575b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venta_cobrada', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('venta_emitida', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_column('venta_emitida')
        batch_op.drop_column('venta_cobrada')

    # ### end Alembic commands ###
