"""Initial migration

Revision ID: 3951959bf3fe
Revises: 
Create Date: 2025-07-03 14:04:44.306349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3951959bf3fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('apellidos', sa.String(length=150), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('comision', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('id_localizador', sa.String(length=100), nullable=False),
    sa.Column('fecha_viaje', sa.String(length=50), nullable=True),
    sa.Column('producto', sa.String(length=100), nullable=True),
    sa.Column('fecha_venta', sa.String(length=50), nullable=True),
    sa.Column('modalidad_pago', sa.String(length=50), nullable=True),
    sa.Column('nombre_pasajero', sa.String(length=100), nullable=True),
    sa.Column('telefono_pasajero', sa.String(length=50), nullable=True),
    sa.Column('mail_pasajero', sa.String(length=100), nullable=True),
    sa.Column('precio_venta_total', sa.Float(), nullable=True),
    sa.Column('hotel_neto', sa.Float(), nullable=True),
    sa.Column('vuelo_neto', sa.Float(), nullable=True),
    sa.Column('traslado_neto', sa.Float(), nullable=True),
    sa.Column('seguro_neto', sa.Float(), nullable=True),
    sa.Column('circuito_neto', sa.Float(), nullable=True),
    sa.Column('crucero_neto', sa.Float(), nullable=True),
    sa.Column('excursion_neto', sa.Float(), nullable=True),
    sa.Column('paquete_neto', sa.Float(), nullable=True),
    sa.Column('localizadores', sa.String(length=200), nullable=True),
    sa.Column('nombre_ejecutivo', sa.String(length=100), nullable=True),
    sa.Column('correo_ejecutivo', sa.String(length=100), nullable=True),
    sa.Column('destino', sa.String(length=100), nullable=True),
    sa.Column('comprobante_venta', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_localizador')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('usuario')
    # ### end Alembic commands ###
