"""Actualización de modelos

Revision ID: 73b950a44507
Revises: 43f103b668df
Create Date: 2025-07-05 15:08:44.457728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b950a44507'
down_revision = '43f103b668df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Ganancia_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comision_ejecutivo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comision_agencia', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_column('comision_agencia')
        batch_op.drop_column('comision_ejecutivo')
        batch_op.drop_column('Ganancia_total')

    # ### end Alembic commands ###
