"""Actualización de modelos

Revision ID: b03f18dc1f3f
Revises: 73b950a44507
Create Date: 2025-07-05 17:44:02.491767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03f18dc1f3f'
down_revision = '73b950a44507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comentarios', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_column('comentarios')
        batch_op.drop_column('bonos')

    # ### end Alembic commands ###
